#!/bin/bash
# Generated by Codery — setup session with Tural, 2026-08-11. Amend via issues in this repo.
#
# Gate: tracking-gate (deny-once)
# PreToolUse hook on Bash. Reads the tool call from stdin, acts only on
# commands matching the gate's pattern, and enforces the rule:
# every PR references its GitHub issue (CLAUDE.md, Two tracking surfaces).
# Every decision is appended to .gate-telemetry.jsonl (gitignored).
#
# Accepted gaps: a body passed via -F <file> is uninspectable from the
# command string; any "#<digits>" occurrence passes, even a spurious one;
# a command string merely mentioning "gh pr create" (e.g. inside an echo)
# trips the deny-once. The CLAUDE_PROJECT_DIR scope check makes this gate a
# no-op whenever the session's project dir and the repo root differ — a
# session driving a git worktree of this repo, or a checkout reached through
# a symlinked path — and the review of the PR remains the second barrier in
# that case.
#
# Fail-open by construction: every error path exits 0 and stdout stays empty
# unless the gate has actually decided to deny.

set -u

GATE="tracking-gate"
MODE="deny-once"
PATTERN='gh[[:space:]]+([^;&|]*[[:space:]])?pr[[:space:]]+create'

# --- stdin: tool_input.command + session_id (missing -> allow silently) ---
INPUT=$(cat)
COMMAND=$(printf '%s' "$INPUT" | jq -r '.tool_input.command // empty' 2>/dev/null)
SESSION_ID=$(printf '%s' "$INPUT" | jq -r '.session_id // empty' 2>/dev/null)
[ -z "$COMMAND" ] && exit 0
[ -z "$SESSION_ID" ] && exit 0

# --- defensive re-check: act only on commands this gate is about ---
printf '%s' "$COMMAND" | grep -Eq "$PATTERN" || exit 0

REPO_ROOT=$(git rev-parse --show-toplevel 2>/dev/null) || exit 0

# --- scope: this gate enforces its own project's rules, nothing else ---
if [ -n "${CLAUDE_PROJECT_DIR:-}" ] && [ "$REPO_ROOT" != "$CLAUDE_PROJECT_DIR" ]; then
  exit 0
fi
# best-effort: a command that first cd's outside this repo is out of scope
FIRST_CD=$(printf '%s' "$COMMAND" | sed -nE 's/^[[:space:]]*cd[[:space:]]+([^[:space:];&|]+).*/\1/p')
if [ -n "$FIRST_CD" ]; then
  CD_TARGET=$(cd "$FIRST_CD" 2>/dev/null && pwd)
  if [ -n "$CD_TARGET" ] && [ "$CD_TARGET" != "$REPO_ROOT" ] && [ "${CD_TARGET#$REPO_ROOT/}" = "$CD_TARGET" ]; then
    exit 0
  fi
fi

log_decision() { # decision
  local file="$REPO_ROOT/.gate-telemetry.jsonl"
  mkdir -p "$(dirname "$file")"
  printf '{"ts":"%s","gate":"%s","decision":"%s","session":"%s"}\n' \
    "$(date -u +%Y-%m-%dT%H:%M:%SZ)" "$GATE" "$1" "$SESSION_ID" >> "$file"
}

deny() {
  log_decision "deny"
  cat <<EOF
{"hookSpecificOutput":{"hookEventName":"PreToolUse","permissionDecision":"deny","permissionDecisionReason":"Tracking gate: this PR-create command references no GitHub issue, and every PR must reference its issue — add the issue number, e.g. Refs #N, or Closes #N when the PR completes the item (CLAUDE.md, Two tracking surfaces). Add the reference and try again — or, if this PR genuinely tracks no issue, run the same command again and it will proceed."}}
EOF
  exit 0
}

gate_check() {
  # rule: the command must reference a GitHub issue (#N)
  printf '%s' "$COMMAND" | grep -Eq '#[0-9]+' && return 0
  return 1
}

if gate_check; then
  log_decision "pass"
  exit 0
fi

if [ "$MODE" = "deny-once" ]; then
  MARKER="/tmp/codery-gate-${GATE}-${SESSION_ID}"
  if [ -f "$MARKER" ]; then
    log_decision "allow-after-deny"
    exit 0
  fi
  touch "$MARKER"
fi

deny
